serhiisol/node-decorators

playground/socket/index.ts
playground/socket/package.json
socket/CHANGELOG.md
socket/README.md
socket/package.json
socket/src/decorators/param.ts
socket/src/socket.ts
types/base.d.ts

* Added wrap option for **@Socket(WrapperClass?)** decorator, now you can pass wrapper class in it, to get extended functionality over the socket, optional parameter, e.g.:
```typescript
class SocketWrapper {
constructor(private socket: SocketIO.Socket) {}
}
```

feat(socket): Socket 1.3.2: Socket parameter WrapperClass

---

express/.npmignore
express/CHANGELOG.md
express/README.md
express/index.ts
express/package.json
express/src/decorators/controller.ts
express/src/decorators/index.ts
express/src/decorators/middleware.ts
express/src/decorators/params.ts
express/src/decorators/route.ts
express/src/express.ts
express/src/index.ts
express/src/meta.ts
playground/express/index.ts
playground/express/package.json
socket/src/decorators/class.ts
socket/src/meta.ts
types/express.d.ts

* Added controller-based middleware - **@Controller(baseUrl: string, [middleware]?)**
* moved route-based middleware to route definition decorator - **@Get(url: string, [middleware]?)**
* renamed **bootstrapControllers** to **attachControllers**
* **@Middleware** moved to deprecated, will be removed in 2.0.0
* **bootstrapControllers** moved to deprecated, will be removed in 2.0.0

feat(express): Express 1.2.0: new middleware, custom route and small fixes

---

README.md
express/src/decorators/controller.ts

This PR fixes:
1) Removed unnecessary deprecated symbol from express controller decorator (closes #24)
2) Cleaned up home doc (closes #25)
👍

chore(docs, express): Removed unnecessary deprecated symbol and cleaned up home doc

---

common/.npmignore
common/CHANGELOG.md
common/README.md
common/package.json
common/src/catch.ts
common/src/interface.ts
common/src/meta.ts
common/tsconfig.json
playground/common/index.ts
types/common.d.ts

This PR implements:
* Moved project back to es5
* **@Catch()** now accepts all passed arguments of the original function and error (closes #31), e.g.:
```typescript
@Catch((volume: number, e: Error) => {
// ...
})
sound(volume: number) {}
```
👍

feat(common): ES5 support, Catch accepts arguments passed into decorated function

---

express/package.json

This should fix typescript complaining `[ts] Cannot find module '@decorators/express'.`

Define types field to package.json

---

express/CHANGELOG.md
express/package.json
express/src/express.ts
express/src/middleware.ts
playground/express/index.ts
playground/express/package.json

This PR fixes:
* `@Injectable` from `@decorators/di` is now optional for controller.
Note: make sure to use `@Injectable` if you need dependency injection in controller.
Closes #70 
* Fixed passing incorrect error object to next handler in case if `ERROR_MIDDLEWARE` wasn't registered

feat(express): Injectable as an option for controller, fix for error middleware

---

mongoose/.npmignore
mongoose/CHANGELOG.md
mongoose/package.json
mongoose/src/mongoose.ts
mongoose/tsconfig.json

* Added ability to not to use `@Injectable` from `@decorators/di` in case if DI is not needed
* Changed library structure

feat(mongoose): 3.0.1 Injectable is not required

---

express/CHANGELOG.md
express/package.json
express/src/express.ts

I had the following issue, which lead me to open this PR:
JSON payload example:
```json
{ "active": false, "appDomainId": 0 }
```
Extract of my code:
```typescript
@Controller('/user')
export default class UserController 
{
@Post('/create')
async create (@Response() res, @Body('active') active: boolean, @Body('appDomainId') appDomainId: number, @Body('data') data: any)
{
console.log(active); // returned complete body { "active": false, "appDomainId": 0 }. Expected false
console.log(appDomainId); // returned complete body { "active": false, "appDomainId": 0 }. Expected 0
if (data)
{
// It always end up here, even if data is undefined.
}
}
}
```

[express] Fixes `getParam` to always return property of `param` when `name` is provided

---

express/src/express.ts

These changes add in the ability to add Controller instances to a express app.
This basically solves my Issue: https://github.com/serhiisol/node-decorators/issues/102
@serhiisol  This implementation worked for me, do you have any concerns, or are there possible side effects?

add attachControllerInstances

---

express/package.json
express/src/decorators/controller.ts
express/src/decorators/route.ts

This is useful if, for example, another annotation wants to set some middlewares on the route or controller. A use case I wanted is adding a `@Validator(...)` annotation which wraps express-validator middlewares and error handling before a controller or route annotation.
It might also be desirable to export `meta.ts` if this is something the library wants to allow the users to do.

Keep middlewares in controllers and routes meta if already set

---

di/CHANGELOG.md
di/package.json

I'm trying to make a update of reflect-metadata due to https://github.com/serhiisol/node-decorators/issues/108, but not sure how to manage the updated "@decorators/di" for express and socket packages, hope can this help :)

feat(di): update reflect-metadata to 0.1.13

---

express/src/decorators/route.ts
express/src/express.ts
express/src/meta.ts

Add the ability to define multiple urs for the same method
**Before:**
```ts
@Controller('/')
class MyController {
...
@Get('/route1', [...])
public route1(@Response() res) {
this.logic(res);
}
@Get('/route2', [...])
public route1(@Response() res) {
this.logic(res);
}
private logic(res) {
res.send('Hello world');
}
}
```
**After:**
```ts
@Controller('/')
class MyController {
...
@Get('/route1', [...])
@Get('/v1/route1', [...])
public route1(@Response() res) {
res.send('Hello world');
}
}
```

feat(express): Allow having multiple route decorators per method

---

README.md
express/src/decorators/params.ts

I have exported two constants Req and Res which are pointing to original full version constants Request and Response , this will eliminate the hassle of adding alias for Request and Response  decorators in imports and also not create any issues with older code which is using full name of Req and Res decorators. 
I have also added  a example in readme.md file to better understand the modification.

feat(express): added shorter version of Request(Req) and Response(Res) decorators

---

express/.eslintrc.json
express/README.md
express/package-lock.json
express/package.json
express/src/decorators/controller.ts
express/src/decorators/params.ts
express/src/decorators/route.ts
express/src/express.ts
express/src/index.ts
express/src/meta.ts
express/src/middleware.ts

@decorators/express 2.8.0
Features:
* Added support of `return value` (closes #120)
* Added support of simple functions as middlewares (closes #118)
* Added `@Status` decorator to send specific status code for routes that don't use `@Res` but use returned value instead
* Removed default args for routes that won't provide any param decorators
Fixes:
* Defining multiple routes for the same method won't merge middlewares, each route will now have own middleware list

feat(express): Express 2.8.0

---

express-openapi/package.json
express-openapi/src/decorators/WithDefinitions.ts

openapi decorator was crashing because WithDefinitions was using getRoutes function to extract routes as  array however due to  recent changes in express decorators  it was receiving undefined on each iterated key.

fix(express-openapi): fixed Openapi package caused by express 2.8.0 update

---

express/src/express.ts

When a controller was not returning  anything or returning a promise which resolves with undefined value server was sending blank response  which is fixed in this commit by adding return value check.

fix(express): fixed issue where server sends the response even if controller did not return anything

---

express-openapi/package-lock.json
express-openapi/package.json
express-openapi/readme.md
express-openapi/src/decorators/path.ts
express-openapi/src/decorators/with-definitions.ts
express-openapi/src/helpers.ts
express-openapi/src/types.ts

* add `options.security` to `enableOpenApi()`
* add `options.components.securitySchemes` to `enableOpenApi()`
* add `options.security` to `@WithDefinitions()`
* add `options.responses` to `@WithDefinitions()`
* add `@Security()` method decorator
* fix route parameter format when generating doc

feat(express-openapi): security and global responses

---

express/README.md
express/package-lock.json
express/package.json
express/src/express.ts

I have added a feature to impliment custom decorators as middlewares with the help of ```attachMiddleware``` function.
example : 
This is my custom ```@Validate(DtoClass)``` decorator code
```typescript
import { attachMiddleware } from "@decorators/express";
import {Request,Response,NextFunction} from '@decorators/express/node_modules/express';
export function Validate(object: any) {
return function (target: any,propertyKey: string,descriptor: PropertyDescriptor) {
attachMiddleware(target,propertyKey,(req : Request,res : Response,next : NextFunction)=>{
// Do some validation and use Next or Res.send according to the validation.
res.send("this is from validate decorator");
})
};
}
```
This is my controller code
```typescript
@Controller("/")
export class MainController {
@Validate("test") …
```

feat(express): use custom decorator as middlewares

---

di/package-lock.json
di/package.json
di/src/container.spec.ts
di/src/decorators/injectable.ts
di/src/index.ts
di/src/root-container.ts

To simplify root singleton providers `Injectable.providedIn='root'`.
Introduces `Injectable` options with `providedIn='root'` option in it to register root provider.
`RootContainer` is exported out of `di` package.

feat(di): provided in root option

---

server/example/app.module.ts
server/example/services/index.ts
server/example/services/posts.service.ts
server/example/services/services.module.ts
server/package-lock.json
server/package.json
server/src/core/application.ts

To simplify root singleton providers via `@Injectable({ providedIn: 'root' })`.
Added `RootContainer` as parent to application container.

feat(server): provided in root injectables
