serhiisol/node-decorators

- CHANGELOG.md
- socket/README.md
- socket/index.d.ts
- socket/package.json
- socket/src/decorators/class.ts
- socket/src/decorators/property.ts
- socket/src/socket.ts
- tsconfig.json
fix(socket): fixed attachController function;
feat(socket): added @OnDisconnect socket decorator
> fix(socket): socket fixes

- README.md
> Example of usage

- CHANGELOG.md
- playground/socket/index.ts
- socket/README.md
- socket/package.json
- socket/src/socket.ts
* added new parameters to middleware functions:
* **@Middleware((io: SocketIO.Server | SocketIO.Namespace, socket: SocketIO.Socket, next: Function) => {})** - registers global (io) middleware
* **@SocketMiddleware((io: SocketIO.Server | SocketIO.Namespace, socket: SocketIO.Socket, packet, next: Function) => {})** - registers socket middleware
> Socket 1.2.1

- playground/socket/index.ts
- playground/socket/package.json
- socket/CHANGELOG.md
- socket/README.md
- socket/package.json
- socket/src/decorators/class.ts
- socket/src/decorators/index.ts
- socket/src/decorators/property.ts
- socket/src/meta.ts
- socket/src/socket.ts
- tsconfig.json
- types/socket.d.ts
* Renamed middleware names to
* **@ServerMiddleware**
* **@GlobalMiddleware**
* **@Middleware**
* Renamed decorators:
* **@Namespace**
* **@GlobalEvent**
* **@Connection**
* **@Disconnect**
* **@Event**
* Added event-based middleware, for socket events
> Socket middleware 1.3.0

- express/CHANGELOG.md
- express/README.md
- express/package.json
- express/src/decorators/middleware.ts
- mongoose/src/mongoose.ts
- package.json
- playground/express/index.ts
- playground/express/package.json
* Added possibility to pass array of middleware funcs into **@Middleware**
> feat(express): Updated middleware to accept array of middlewares

- express/README.md
- express/src/decorators/middleware.ts
- playground/socket/index.ts
- playground/socket/package.json
- socket/CHANGELOG.md
- socket/README.md
- socket/package.json
- socket/src/decorators/class.ts
* Added possibility to pass array of middleware funcs into:
* **@ServerMiddleware**
* **@GlobalMiddleware**
* **@Middleware**
> feat(socket): Controller based middleware decorators can accept now array of middleware functions

- co/package.json
- express/package.json
- mongoose/package.json
- package.json
- playground/co/package.json
- playground/express/package.json
- playground/mongoose/package.json
- playground/socket/package.json
- socket/package.json
Switch to >= to allow all node engine versions higher than declared
> Update node engine dependency version in package.json files

- mongoose/CHANGELOG.md
- mongoose/README.md
- mongoose/package.json
- mongoose/src/decorators/model.ts
- mongoose/src/decorators/schema.ts
* Add options parameter to Model decorator
* Mark Set and Option decorator as deprecated (emit console warning)
* Update README.md accordingly
> Add SchemaTypeOpts as options parameter to Model decorator

- mongoose/CHANGELOG.md
- mongoose/README.md
- mongoose/package.json
- mongoose/src/interfaces.ts
- mongoose/src/meta.ts
- mongoose/src/mongoose.ts
- playground/mongoose/model.ts
This PR fixes:
1) Model DI (closes #35)
2) Cleaned up README (closes #33)
👍
> feat(mongoose): Model DI

- common/CHANGELOG.md
- common/package.json
- common/src/catch.ts
* Fix for **@Catch()** to provide proper arguments if original function returns Promise (async function)
> fix(common): Catch - fixed for async functions

- mongoose/CHANGELOG.md
- mongoose/README.md
- mongoose/index.ts
- mongoose/package.json
- mongoose/src/decorators/index.ts
- mongoose/src/decorators/schema.ts
- mongoose/src/index.ts
- mongoose/src/mongoose.ts
- mongoose/tsconfig.json
- package.json
- playground/mongoose/index.ts
- playground/mongoose/model.ts
- playground/mongoose/package.json
* Fixed model ctx for DI (closes #39)
> Mongoose 1.2.1

- mongoose/src/decorators/model.ts
- mongoose/src/interfaces.ts
- mongoose/src/mongoose.ts
Hi @serhiisol,
Kindly review this PR for #44 and let me know if it's acceptable. 
Thanks.
> Fix issue #44

- common/src/suppress.ts
This PR adds error resiliance to the `SuppressConsole` decorator. Errors thrown in the decorated method  (sync or async) don't disable `console.log` for the whole app.
Example:
```typescript
const timeout = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
class Tortoise {
@SuppressConsole()
async sound(volume: number) {
// unlike other animals, tortoises are slow
await timeout(2000);
console.log(`a sound so silent, the console doesn't even hear it`);
throw new Error(`Tortoises can't really scream`);
}
}
const michelangelo = new Tortoise();
console.log('what does the tortoise say?');
michelangelo.sound(9001)
.then(() => console.log('worked!'))
.catch(() => console.log('oh no! :-('));
setTimout(() => console.log('logging still works, right?'), 5000);
```
Before this PR: …
> fix(common): Rethrow errors in suppress decorator

- express/package.json
- express/src/express.ts
- express/src/interface.ts
- express/src/meta.ts
- playground/express/index.ts
* Fixed incorrect typings for **attachControllers** function
Closes #50
> fix(express): Fixed incorrect typings for attachControllers function

- playground/socket/index.ts
- playground/socket/package.json
- socket/.npmignore
- socket/CHANGELOG.md
- socket/README.md
- socket/package.json
- socket/src/decorators/controller.ts
- socket/src/decorators/events.ts
- socket/src/decorators/index.ts
- socket/src/decorators/middleware.ts
- socket/src/decorators/params.ts
- socket/src/index.ts
- socket/src/interface.ts
- socket/src/socket.ts
- socket/src/utils.ts
- socket/tsconfig.json
- tsconfig.json
* Socket object availability in connection event
* Adusted types
Closes #53
> fix(socket): Socket object availability in connection event

- .vscode/launch.json
- di/.npmignore
- di/index.ts
- di/package.json
- di/src/container.ts
- di/src/errors/error.ts
- di/src/errors/missing-provider.ts
- di/src/errors/recursive-provider.ts
- di/tsconfig.json
- playground/di/index.ts
> chore(di): added extra error messages

- socket/CHANGELOG.md
- socket/README.md
- socket/package.json
- socket/src/middleware.ts
This PR fixes:
* Updated README file to the latest version, fixes #75
> docs(socket): Updated README

- express/src/express.ts
Added support for creating controllers on express Router instance #77
> :sparkles: Added Router  support for attach controllers #77

- express/src/express.ts
Fixed the createController typings aswell.
> Added Router  support for attach controllers #77

- express/README.md
- express/package.json
- express/src/express.ts
#77 
Sorry for the double request forgot to add the Router type to registerController functions as well
> #77 Fix registerController type

- .gitignore
- express/.npmignore
- express/CHANGELOG.md
- express/README.md
- express/package.json
- express/src/express.ts
- express/tsconfig.json
- playground/express/index.ts
- playground/express/package.json
- playground/express/tsconfig.json
* Global error middleware also intercepts errors in async method handlers, closes #82 
* Changed library structure
> fix(socket): Global error middleware async errors

- socket/CHANGELOG.md
- socket/package.json
- socket/src/socket.ts
https://github.com/serhiisol/node-decorators/issues/85
> fix order in sort 

- di/src/container.spec.ts
- di/src/container.ts
> fix dep tree to avoid RecursiveProviderError

- di/CHANGELOG.md
- di/package.json
> chore(di): DI@1.0.2 Bump version

- .vscode/launch.json
- .vscode/settings.json
- express/CHANGELOG.md
- express/package.json
- express/src/decorators/index.ts
- express/src/decorators/params.ts
- express/src/decorators/route.ts
- express/src/express.ts
- express/src/index.ts
- express/src/middleware.ts
- playground/express/index.ts
- playground/express/package.json
* Added support for `async` middleware
* `express` and `@decorators/di` as `peerDependencies`
> feat(express): Express@2.3.0 Added support of async middleware

- playground/socket/index.ts
- playground/socket/package.json
- socket/CHANGELOG.md
- socket/README.md
- socket/index.ts
- socket/package.json
- socket/src/decorators/controller.ts
- socket/src/decorators/events.ts
- socket/src/index.ts
- socket/src/meta.ts
- socket/src/middleware.ts
- socket/src/socket.ts
- socket/tsconfig.json
* Changed library structure
* Fixed interfaces
* Added new interface to implement for server middleware `ServerMiddleware`, controller `Middleware` interface remains the same
* Updated versions of dependencies, like `socket.io` and `@decorators/di`
Closes #98
> feat: Updated dependencies, fixed types issues, added ServerMiddleware interface, improved library structure

- playground/socket/package.json
- socket/package.json
- socket/src/middleware.ts
* Made global middleware optional
* Made dependencies as peerDependencies
Closes #75
> Feat: optional global middleware

- express/package-lock.json
- express/package.json
- express/src/decorators/controller.ts
- express/src/decorators/route.ts
- express/src/express.ts
- express/src/meta.ts
- express/src/middleware.ts
* Added option to add RouterOptions to the controller 
Closes #104
> feat(express): controller router params

- express/package.json
- express/src/middleware.ts
> fix(express): added fix to handle arrow functions as middlewares

- socket/package-lock.json
- socket/package.json
- socket/src/middleware.ts
- socket/src/socket.ts
* Updated di version to 2.0.0
* Fixed controller middleware not being triggered when `connect` event is triggered
> feat(socket): updated di version

- express/package-lock.json
- express/package.json
- express/src/express.ts
> fix(express): fixed incorrectly applied middleware

- express-openapi/package.json
- express-openapi/readme.md
- express-openapi/src/decorators/path.ts
- express-openapi/src/types.ts
* add `schema` to `Param()`
* add `options.contentMediaType` to `Param()`
> fix(express-openapi): param schema

- server/.eslintrc.json
- server/example/app.module.ts
- server/integration/core/pipes/src/app.module.ts
- server/integration/core/scopes/src/modules/posts.module.ts
- server/integration/core/scopes/src/modules/users.module.ts
- server/package.json
- server/src/core/decorators/module.ts
- server/src/core/helpers/constants/constants.ts
- server/src/core/helpers/decorators.ts
- server/src/core/helpers/errors/api-error.ts
- server/src/core/helpers/reflector.ts
- server/src/core/types.ts
- server/src/platforms/express/express-adapter.ts
- server/src/platforms/http/decorators/params.ts
- server/src/platforms/http/helpers/constants/parameter-type.ts
- server/src/platforms/http/helpers/http-application-adapter.ts
- server/src/platforms/http/helpers/metadata-scanner.ts
- server/src/platforms/http/helpers/route-resolver.ts
- server/src/platforms/http/http.module.ts
- server/src/platforms/http/index.ts
- server/src/platforms/http/types.ts
Core:
* `Decorate` will support properties
Http:
* `serveStatic`
* Renamed `ParameterType` keys
* `MetadataScanner`
Misc:
* eslint updates
> feat(server): decorate to support properties, serveStatic, ParameterType updates

- express/.eslintrc.json
- express/.vscode/launch.json
- express/README.md
- express/example/index.ts
- express/example/tsconfig.json
- express/package-lock.json
- express/package.json
- express/src/container.ts
- express/src/decorators/controller.ts
- express/src/express.ts
- express/src/index.ts
- express/src/middleware.ts
- express/src/types.ts
- express/tsconfig.example.json
- express/tsconfig.json
- express/tsconfig.lint.json
Major 3.0.0 Release
Features:
* added support of @decorators/di@3.0.0
* marks controller as injectable automatically
Breaking changes:
* @decorators/di doesn't export Container anymore, so @decorators/express exports its root Container.
> feat(express): release 3.0.0

- express-openapi/package-lock.json
- express-openapi/package.json
- express-openapi/src/helpers.ts
- express-openapi/tsconfig.json
Major Release 2.0.0
* updated @decorators/express@3.0.0
> feat(express-openapi): release 2.0.0

- server/README.md
- server/package-lock.json
- server/package.json
> fix(server): missing typeVersions, release beta.3

- express-openapi/package-lock.json
- express-openapi/package.json
- express-openapi/src/decorators/schema.ts
- express-openapi/src/types.ts
* Adds ability to mark property as nullable (resolves #179)
> feat(express-opeapi): added nullable option

- server/example/pipes/server.pipe.ts
- server/package-lock.json
- server/package.json
- server/src/core/helpers/errors/api-error.ts
- server/src/core/helpers/pipe/pipeline.ts
- server/src/platforms/express/express-adapter.ts
- server/src/platforms/http/helpers/http-application-adapter.ts
- server/src/platforms/http/helpers/http-context.ts
- server/src/platforms/http/helpers/route-handler.ts
- server/src/platforms/http/helpers/route-resolver.ts
1.0.0-beta.4 release:
* Adds custom parameter decorator error handling - pipes will receive error for handling (#174)
* Adds error handling for `render` process (#173, #175)
> feat(server): updated error handling

- server/example/modules/posts/decorators/access-param.ts
- server/example/modules/posts/posts.controller.ts
- server/src/core/helpers/param-validator.ts
- server/src/core/types.ts
- server/src/platforms/http/helpers/http-application-adapter.ts
- server/src/platforms/http/helpers/http-context.ts
- server/src/platforms/http/helpers/route-handler.ts
- server/src/platforms/http/helpers/route-resolver.ts
* updated param validation
* param extraction returns promise
> feat(server): updated param validation, param extraction returns promise

- server/src/core/helpers/errors/index.ts
- server/src/core/helpers/errors/not-found.ts
NotFoundtError -> NotFoundError
> fix(server): typo

- server/README.md
- server/example/modules/posts/decorators/access-param.ts
- server/example/modules/posts/posts.controller.ts
- server/integration/http/params/src/app.controller.ts
- server/integration/http/params/test/express.spec.ts
- server/package-lock.json
- server/package.json
- server/src/core/helpers/decorators.ts
- server/src/core/helpers/param-validator.ts
- server/src/core/types.ts
- server/src/core/utils.ts
- server/src/platforms/http/decorators/params.ts
* Removes standard type validation
* Adds custom param validators:
```ts
post(@Params('id', (id) => !IsNaN(Number(id))) id: number) {}
```
Resolves #183
> feat(server): updated param validation - introduce custom param validators

- server/README.md
- server/example/app.module.ts
- server/example/modules/posts/posts.controller.ts
- server/integration/swagger/src/app.controller.ts
- server/integration/swagger/src/app.module.ts
- server/integration/swagger/test/express.spec.ts
- server/integration/swagger/tsconfig.json
- server/package-lock.json
- server/package.json
- server/src/platforms/swagger/decorators/api-operation.ts
- server/src/platforms/swagger/decorators/api-parameter.ts
- server/src/platforms/swagger/decorators/api-response.ts
- server/src/platforms/swagger/decorators/api-security.ts
- server/src/platforms/swagger/decorators/index.ts
- server/src/platforms/swagger/helpers/constants/constants.ts
- server/src/platforms/swagger/helpers/constants/index.ts
- server/src/platforms/swagger/helpers/constants/injectables.ts
- server/src/platforms/swagger/helpers/index.ts
- server/src/platforms/swagger/helpers/swagger-ui/index.ts
- server/src/platforms/swagger/helpers/swagger-ui/swagger-dark.css
- server/src/platforms/swagger/helpers/swagger-ui/swagger-document.ts
- server/src/platforms/swagger/helpers/swagger-ui/swagger-resolver.ts
- server/src/platforms/swagger/helpers/swagger-ui/utils.ts
- server/src/platforms/swagger/index.ts
- server/src/platforms/swagger/swagger.module.ts
- server/src/platforms/swagger/types.ts
- server/tsconfig.json
> feat(server): swagger platform

- .github/PULL_REQUEST_TEMPLATE.md
- server/example/modules/posts/posts.controller.ts
- server/package-lock.json
- server/package.json
- server/src/platforms/swagger/decorators/index.ts
Missing export of `ApiResponseSchema`.
Exports of `ApiResponseSchema`
> fix(server): swagger - fixed missing export

- .github/PULL_REQUEST_TEMPLATE.md
- server/README.md
- tools/git-pre-push
- tools/install-hook
> chore: added git scripts

- server/README.md
- server/example/app.module.ts
- server/example/main.ts
- server/integration/core/app-version/test/express.spec.ts
- server/integration/core/app-version/test/fastify.spec.ts
- server/integration/core/custom-decorators/test/express.spec.ts
- server/integration/core/custom-decorators/test/fastify.spec.ts
- server/integration/core/pipes/test/express.spec.ts
- server/integration/core/pipes/test/fastify.spec.ts
- server/integration/core/scopes/test/express.spec.ts
- server/integration/core/scopes/test/fastify.spec.ts
- server/integration/http/metadata-scanner/test/express.spec.ts
- server/integration/http/metadata-scanner/test/fastify.spec.ts
- server/integration/http/params/src/app.controller.ts
- server/integration/http/params/test/fastify.spec.ts
- server/integration/http/routes/test/fastify.spec.ts
- server/integration/swagger/test/fastify.spec.ts
- server/package-lock.json
- server/package.json
- server/src/core/helpers/decorators.ts
- server/src/core/utils.ts
- server/src/platforms/express/express-adapter.ts
- server/src/platforms/fastify/fastify-adapter.ts
- server/src/platforms/fastify/index.ts
- server/src/platforms/http/helpers/http-application-adapter.ts
- server/src/platforms/http/helpers/route-handler.ts
- server/src/platforms/http/http.module.ts
- server/src/platforms/swagger/helpers/swagger-ui/swagger-resolver.ts
- server/tsconfig.json
- tools/git-pre-push
Requested support of Fastify
* Fastify adapter was added
* Adjustments to support fastify
* `createParamDecorator` and `adapter.getParam` factory will return function instead, promise-like params are causing delays in execution while awaiting for them in the handler.
> feat(server): beta.11 - fastify adapter

- server/.vscode/launch.json
- server/README.md
- server/example/app.module.ts
- server/example/main.ts
- server/integration/core/app-version/test/koa.spec.ts
- server/integration/core/custom-decorators/test/koa.spec.ts
- server/integration/core/pipes/test/koa.spec.ts
- server/integration/core/scopes/test/koa.spec.ts
- server/integration/http/metadata-scanner/test/koa.spec.ts
- server/integration/http/params/test/koa.spec.ts
- server/integration/http/routes/test/koa.spec.ts
- server/integration/swagger/test/koa.spec.ts
- server/package-lock.json
- server/package.json
- server/src/platforms/express/express-adapter.ts
- server/src/platforms/fastify/fastify-adapter.ts
- server/src/platforms/http/helpers/http-application-adapter.ts
- server/src/platforms/http/helpers/route-resolver.ts
- server/src/platforms/http/types.ts
- server/src/platforms/koa/index.ts
- server/src/platforms/koa/koa-adapter.ts
- server/src/platforms/swagger/helpers/swagger-ui/swagger-resolver.ts
- server/tsconfig.json
Requested Koa adapter.
* Koa adapter was added
* Adjustments to support koa
* `adapter.route` was removed in favor of `adapter.routes`, adapters can now register all routes at once (for example using routers) instead of one at a time.
> feat(server): beta.12 - koa adapter

- server/integration/sockets/events/src/app.controller.ts
- server/integration/sockets/events/test/socket-io.spec.ts
- server/integration/sockets/params/src/app.controller.ts
- server/integration/sockets/params/test/socket-io.spec.ts
- server/package-lock.json
- server/package.json
- server/src/core/helpers/decorators.ts
- server/src/core/helpers/param-validator.ts
- server/src/platforms/http/http.module.ts
- server/src/platforms/socket-io/socket-io-adapter.ts
- server/src/platforms/sockets/decorators/events.ts
- server/src/platforms/sockets/helpers/constants/event-type.ts
- server/src/platforms/sockets/helpers/event-handler.ts
- server/src/platforms/sockets/helpers/event-resolver.ts
- server/src/platforms/sockets/helpers/sockets-application-adapter.ts
- server/src/platforms/sockets/sockets.module.ts
* Fixed `Decorate` replacing class parameter
* Added `getAdapter` to `HttpModule`
* Removed `@Disconnecting` event
* Added `getAdapter` to `SocketsModule`
* Added `adapter.disconnect` if error occurs on `connection`
> fix(server): beta.18 - fixed Decorate replacing parameter, removed disconnecting event in sockets
